### ISSUE TITLE
Reporte de Practica

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Band-hi#2]
[Reporte Practica DLL.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Band-hi/files/6287957/Reporte.Practica.DLL.pdf)

**Comment by christopheremv** [comment]
calificación 20 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
